### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by AdeelWajid** [krispybyte/Simple-Rust-Base#2]
[*] RustClient[*] RustClient.exe Window @ 0x0000000000050718
[*] GameAssembly.dll @ 0x0000000000000000
[*] UnityPlayer.dll @ 0x0000000000000000

only shows this, nothing happens
![Screenshot (102)](https://user-images.githubusercontent.com/56066183/148645640-4351dc7c-54fc-42c0-b686-8316735cbeb2.png)

**Comment by krispybyte** [comment]
This is just a source, all the functions inside the controller folder are empty, you switch them with your own bypass communication functions
