### ISSUE TITLE
👍 

### ISSUE THREAD

**Issue by Tyler-Admin** [krispybyte/Simple-Rust-Base#3]
Good looking base. Looks like you got a little lazy and switched up the case type? or forgot to change it in some locations. there are definitely better c++ practices you could've followed but who am I to say that 😆. Definitely improved since the last time we talked. Seeb this on my GitHub so figured id check it out :) 
Sincerely, Tyler.

**Comment by krispybyte** [comment]
thanks, add me on discord if you wanna talk again, i dont think i have you added
krispy#8390

**Comment by Tyler-Admin** [comment]
added by llamas
